Install pkgs for testnet. Ganache-cli in truffle.js
I was testing with Ganache, but the project requirement is to use
ganache-cli for testing.  So, update the port to 8545 for cli.

Add what's needed to also be able to test on Rinkeby testnet with
Infura.  I had to "npm install" dotenv and truffle-hdwallet-provider.

Reference:
https://medium.com/coinmonks/deploy-your-smart-contract-directly-from-truffle-with-infura-ba1e1f1d40c2

Compiling & migrating & doing manual testing with the web browser worked
fine.

Unfortunately, "truffle test --network rinkeby" only has 7
passing tests and 7 failing tests.  Some of the failures are because
catchRevert expects the Ganache revert messages & not the Rinkeby revert
messages.  But, a couple need further debug.  Here is the output:

truffle test --network rinkeby
Using network 'rinkeby'.

  Contract: AcmeWidgetCo
    ✓ accounts[0] (deployer) should be an admin (401ms)
    ✓ Test adding admin, tester, salesdist, customers (73165ms)
    1) Test that a registered account can't be registered again.

    Events emitted during test:
    ---------------------------

    NewCustomer(_newCustomerRegistered: <indexed>)

    ---------------------------
    2) Test admin populating list of factories and test sites

    Events emitted during test:
    ---------------------------

    NewFactory(_factoryCount: <indexed>, _factory: Factory1 Shanghai)
    NewFactory(_factoryCount: <indexed>, _factory: Factory2 Taipei)
    NewTestSite(_testSiteCount: <indexed>, _testSite: TS1 Singapore)
    NewTestSite(_testSiteCount: <indexed>, _testSite: TS2 Osaka)

    ---------------------------
    ✓ Test tester recording widget result (17258ms)
Error: Invalid JSON RPC response: ""
    at Object.InvalidResponse (/home/nathalie/Blockchain/ConsensysDevAcademy/ConsensysDevAcademyQ4CY18_project/node_modules/truffle-hdwallet-provider/dist/webpack:/truffle-hdwallet-provider/Users/gnidan/src/work/truffle/node_modules/web3-providers-http/node_modules/web3-core-helpers/src/errors.js:42:1)
    at e.n.onreadystatechange (/home/nathalie/Blockchain/ConsensysDevAcademy/ConsensysDevAcademyQ4CY18_project/node_modules/truffle-hdwallet-provider/dist/webpack:/truffle-hdwallet-provider/Users/gnidan/src/work/truffle/node_modules/web3-providers-http/src/index.js:92:1)
    at e.t.dispatchEvent (/home/nathalie/Blockchain/ConsensysDevAcademy/ConsensysDevAcademyQ4CY18_project/node_modules/truffle-hdwallet-provider/dist/webpack:/truffle-hdwallet-provider/Users/gnidan/src/work/truffle/node_modules/xhr2-cookies/dist/xml-http-request-event-target.js:34:1)
    at e._setReadyState (/home/nathalie/Blockchain/ConsensysDevAcademy/ConsensysDevAcademyQ4CY18_project/node_modules/truffle-hdwallet-provider/dist/webpack:/truffle-hdwallet-provider/Users/gnidan/src/work/truffle/node_modules/xhr2-cookies/dist/xml-http-request.js:208:1)
    at e._onHttpRequestError (/home/nathalie/Blockchain/ConsensysDevAcademy/ConsensysDevAcademyQ4CY18_project/node_modules/truffle-hdwallet-provider/dist/webpack:/truffle-hdwallet-provider/Users/gnidan/src/work/truffle/node_modules/xhr2-cookies/dist/xml-http-request.js:349:1)
    at ClientRequest.<anonymous> (/home/nathalie/Blockchain/ConsensysDevAcademy/ConsensysDevAcademyQ4CY18_project/node_modules/truffle-hdwallet-provider/dist/webpack:/truffle-hdwallet-provider/Users/gnidan/src/work/truffle/node_modules/xhr2-cookies/dist/xml-http-request.js:252:47)
    at ClientRequest.emit (events.js:182:13)
    at TLSSocket.socketErrorListener (_http_client.js:399:9)
    at TLSSocket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process.internalTickCallback (internal/process/next_tick.js:72:19)
    ✓ Test that additional factory and test sites are usable (75716ms)
    ✓ Test that the recorded widgets in the expected bins (2240ms)
    ✓ Test that sales distributor can update bin unit price. (70654ms)
    ✓ Test that sales distributor can update the bin mask. (59687ms)
    3) Test that customer can only buy widgets that cost <= their msg.value.

    Events emitted during test:
    ---------------------------

    NewTestedWidget(_serial: <indexed>, _factory: <indexed>, _testSite: 1, _results: 4294967295, _widgetCount: 3, _bin: <indexed>, _binCount: 2)
    NewTestedWidget(_serial: <indexed>, _factory: <indexed>, _testSite: 2, _results: 4294967295, _widgetCount: 4, _bin: <indexed>, _binCount: 3)
    NewTestedWidget(_serial: <indexed>, _factory: <indexed>, _testSite: 1, _results: 4294967295, _widgetCount: 5, _bin: <indexed>, _binCount: 4)
    NewTestedWidget(_serial: <indexed>, _factory: <indexed>, _testSite: 2, _results: 4294967295, _widgetCount: 6, _bin: <indexed>, _binCount: 5)

    ---------------------------
    4) Test customer can't buy more widgets than available even with sufficent msg.value.

    Events emitted during test:
    ---------------------------

    ---------------------------
    5) Test that customer can't buy when circuit breaker stops contract.

    Events emitted during test:
    ---------------------------

    ---------------------------
    6) Test that customer can buy multiple widgets from same bin in 1 transaction.

    Events emitted during test:
    ---------------------------

    ---------------------------
    7) Test that admin can withdraw funds from contract.

    Events emitted during test:
    ---------------------------

    ---------------------------

  7 passing (12m)
  7 failing

  1) Contract: AcmeWidgetCo
       Test that a registered account can't be registered again.:
     AssertionError: Expected an error starting with 'VM Exception while processing transaction: revert' but got 'Transaction: 0x567cff93c1e3bfd6d707846877c680fe2fe6720e60b0b753d1114bf7dbedbad8 exited with an error (status 0).
Please check that the transaction:
    - satisfies all conditions set by Solidity `require` statements.
    - does not trigger a Solidity `revert` statement.
' instead
      at tryCatch (test/exceptions.js:10:9)
      at process.internalTickCallback (internal/process/next_tick.js:77:7)

  2) Contract: AcmeWidgetCo
       Test admin populating list of factories and test sites:
     Error: Could not connect to your Ethereum client. Please check that your Ethereum client:
    - is running
    - is accepting RPC connections (i.e., "--rpc" option is used in geth)
    - is accessible over the network
    - is properly configured in your Truffle configuration file (truffle.js)

      at ProviderError.ExtendableError (/home/nathalie/.nvm/versions/node/v11.2.0/lib/node_modules/truffle/build/webpack:/packages/truffle-error/index.js:10:1)
      at new ProviderError (/home/nathalie/.nvm/versions/node/v11.2.0/lib/node_modules/truffle/build/webpack:/packages/truffle-provider/error.js:17:1)
      at /home/nathalie/.nvm/versions/node/v11.2.0/lib/node_modules/truffle/build/webpack:/packages/truffle-provider/wrapper.js:71:1
      at /home/nathalie/.nvm/versions/node/v11.2.0/lib/node_modules/truffle/build/webpack:/packages/truffle-provider/wrapper.js:129:1
      at node_modules/truffle-hdwallet-provider/dist/webpack:/truffle-hdwallet-provider/Users/gnidan/src/work/truffle/node_modules/web3-provider-engine/index.js:157:1
      at node_modules/truffle-hdwallet-provider/dist/webpack:/truffle-hdwallet-provider/Users/gnidan/src/work/truffle/node_modules/async/internal/once.js:12:1
      at d (node_modules/truffle-hdwallet-provider/dist/webpack:/truffle-hdwallet-provider/Users/gnidan/src/work/truffle/node_modules/async/internal/eachOfLimit.js:61:1)
      at node_modules/truffle-hdwallet-provider/dist/webpack:/truffle-hdwallet-provider/Users/gnidan/src/work/truffle/node_modules/async/internal/eachOfLimit.js:71:1
      at e.default (node_modules/truffle-hdwallet-provider/dist/webpack:/truffle-hdwallet-provider/Users/gnidan/src/work/truffle/node_modules/async/eachLimit.js:43:1)
      at node_modules/truffle-hdwallet-provider/dist/webpack:/truffle-hdwallet-provider/Users/gnidan/src/work/truffle/node_modules/async/internal/doLimit.js:9:1
      at s (node_modules/truffle-hdwallet-provider/dist/webpack:/truffle-hdwallet-provider/Users/gnidan/src/work/truffle/node_modules/web3-provider-engine/index.js:134:1)
      at node_modules/truffle-hdwallet-provider/dist/webpack:/truffle-hdwallet-provider/Users/gnidan/src/work/truffle/node_modules/web3-provider-engine/subproviders/provider.js:17:1
      at e.n.onreadystatechange (node_modules/truffle-hdwallet-provider/dist/webpack:/truffle-hdwallet-provider/Users/gnidan/src/work/truffle/node_modules/web3-providers-http/src/index.js:96:1)
      at e.t.dispatchEvent (node_modules/truffle-hdwallet-provider/dist/webpack:/truffle-hdwallet-provider/Users/gnidan/src/work/truffle/node_modules/xhr2-cookies/dist/xml-http-request-event-target.js:34:1)
      at e._setReadyState (node_modules/truffle-hdwallet-provider/dist/webpack:/truffle-hdwallet-provider/Users/gnidan/src/work/truffle/node_modules/xhr2-cookies/dist/xml-http-request.js:208:1)
      at e._onHttpRequestError (node_modules/truffle-hdwallet-provider/dist/webpack:/truffle-hdwallet-provider/Users/gnidan/src/work/truffle/node_modules/xhr2-cookies/dist/xml-http-request.js:349:1)
      at ClientRequest.<anonymous> (node_modules/truffle-hdwallet-provider/dist/webpack:/truffle-hdwallet-provider/Users/gnidan/src/work/truffle/node_modules/xhr2-cookies/dist/xml-http-request.js:252:47)
      at TLSSocket.socketErrorListener (_http_client.js:399:9)
      at emitErrorNT (internal/streams/destroy.js:82:8)
      at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
      at process.internalTickCallback (internal/process/next_tick.js:72:19)

  3) Contract: AcmeWidgetCo
       Test that customer can only buy widgets that cost <= their msg.value.:
     AssertionError: Expected an error starting with 'VM Exception while processing transaction: revert' but got 'Transaction: 0x6eb79e830469f8da8daa83bf6e7f32ece70314048261a61d7f960af8ed36d860 exited with an error (status 0).
Please check that the transaction:
    - satisfies all conditions set by Solidity `require` statements.
    - does not trigger a Solidity `revert` statement.
' instead
      at tryCatch (test/exceptions.js:10:9)
      at process.internalTickCallback (internal/process/next_tick.js:77:7)

  4) Contract: AcmeWidgetCo
       Test customer can't buy more widgets than available even with sufficent msg.value.:
     AssertionError: Expected an error starting with 'VM Exception while processing transaction: revert' but got 'insufficient funds for gas * price + value' instead
      at tryCatch (test/exceptions.js:10:9)
      at process.internalTickCallback (internal/process/next_tick.js:77:7)

  5) Contract: AcmeWidgetCo
       Test that customer can't buy when circuit breaker stops contract.:
     AssertionError: Expected an error starting with 'VM Exception while processing transaction: revert' but got 'Transaction: 0x8b137a7f9c39117952f66b30dc1765e62db7f813e09b60205830cd647148ef94 exited with an error (status 0).
Please check that the transaction:
    - satisfies all conditions set by Solidity `require` statements.
    - does not trigger a Solidity `revert` statement.
' instead
      at tryCatch (test/exceptions.js:10:9)
      at process.internalTickCallback (internal/process/next_tick.js:77:7)

  6) Contract: AcmeWidgetCo
       Test that customer can buy multiple widgets from same bin in 1 transaction.:
     Error: Transaction: 0x38dfe98645de7baf89f0921b6efeecec0a992f418948c7cb6caed71aa09b8cb5 exited with an error (status 0).
Please check that the transaction:
    - satisfies all conditions set by Solidity `require` statements.
    - does not trigger a Solidity `revert` statement.

      at StatusError.ExtendableError (/home/nathalie/.nvm/versions/node/v11.2.0/lib/node_modules/truffle/build/webpack:/packages/truffle-error/index.js:10:1)
      at new StatusError (/home/nathalie/.nvm/versions/node/v11.2.0/lib/node_modules/truffle/build/webpack:/packages/truffle-contract/statuserror.js:29:1)
      at Object.callback (/home/nathalie/.nvm/versions/node/v11.2.0/lib/node_modules/truffle/build/webpack:/packages/truffle-contract/contract.js:181:1)
      at /home/nathalie/.nvm/versions/node/v11.2.0/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/method.js:142:1
      at /home/nathalie/.nvm/versions/node/v11.2.0/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/requestmanager.js:89:1
      at /home/nathalie/.nvm/versions/node/v11.2.0/lib/node_modules/truffle/build/webpack:/packages/truffle-provider/wrapper.js:134:1
      at node_modules/truffle-hdwallet-provider/dist/webpack:/truffle-hdwallet-provider/Users/gnidan/src/work/truffle/node_modules/web3-provider-engine/index.js:159:1
      at node_modules/truffle-hdwallet-provider/dist/webpack:/truffle-hdwallet-provider/Users/gnidan/src/work/truffle/node_modules/async/internal/once.js:12:1
      at d (node_modules/truffle-hdwallet-provider/dist/webpack:/truffle-hdwallet-provider/Users/gnidan/src/work/truffle/node_modules/async/internal/eachOfLimit.js:61:1)
      at node_modules/truffle-hdwallet-provider/dist/webpack:/truffle-hdwallet-provider/Users/gnidan/src/work/truffle/node_modules/async/internal/eachOfLimit.js:71:1
      at e.default (node_modules/truffle-hdwallet-provider/dist/webpack:/truffle-hdwallet-provider/Users/gnidan/src/work/truffle/node_modules/async/eachLimit.js:43:1)
      at node_modules/truffle-hdwallet-provider/dist/webpack:/truffle-hdwallet-provider/Users/gnidan/src/work/truffle/node_modules/async/internal/doLimit.js:9:1
      at s (node_modules/truffle-hdwallet-provider/dist/webpack:/truffle-hdwallet-provider/Users/gnidan/src/work/truffle/node_modules/web3-provider-engine/index.js:134:1)
      at node_modules/truffle-hdwallet-provider/dist/webpack:/truffle-hdwallet-provider/Users/gnidan/src/work/truffle/node_modules/web3-provider-engine/subproviders/provider.js:19:1
      at e.n.onreadystatechange (node_modules/truffle-hdwallet-provider/dist/webpack:/truffle-hdwallet-provider/Users/gnidan/src/work/truffle/node_modules/web3-providers-http/src/index.js:96:1)
      at e.t.dispatchEvent (node_modules/truffle-hdwallet-provider/dist/webpack:/truffle-hdwallet-provider/Users/gnidan/src/work/truffle/node_modules/xhr2-cookies/dist/xml-http-request-event-target.js:34:1)
      at e._setReadyState (node_modules/truffle-hdwallet-provider/dist/webpack:/truffle-hdwallet-provider/Users/gnidan/src/work/truffle/node_modules/xhr2-cookies/dist/xml-http-request.js:208:1)
      at e._onHttpResponseEnd (node_modules/truffle-hdwallet-provider/dist/webpack:/truffle-hdwallet-provider/Users/gnidan/src/work/truffle/node_modules/xhr2-cookies/dist/xml-http-request.js:318:1)
      at IncomingMessage.<anonymous> (node_modules/truffle-hdwallet-provider/dist/webpack:/truffle-hdwallet-provider/Users/gnidan/src/work/truffle/node_modules/xhr2-cookies/dist/xml-http-request.js:289:47)
      at endReadableNT (_stream_readable.js:1098:12)
      at process.internalTickCallback (internal/process/next_tick.js:72:19)

  7) Contract: AcmeWidgetCo
       Test that admin can withdraw funds from contract.:

      Balance should have been 600000000000000000 from previous sale.
      + expected - actual

      -0
      +600000000000000000

      at Context.it (test/TestAcmeWidgetCo.js:293:16)
      at process.internalTickCallback (internal/process/next_tick.js:77:7)

Signed-off-by: Nathalie C. Chan King Choy <nathalie.ckc.123@gmail.com>